const sportChannel = [
    { href: "fox-sport-2-hd", title: "FOX SPORT 2 HD", logo: "fox" },
    { href: "sportv-3-hd", title: "SPORTV 3 HD", logo: "sporttv" },
    { href: "sportv-2-hd", title: "SPORTV 2 HD", logo: "sporttv" },
    { href: "sportv-hd", title: "SPORTV HD ", logo: "sporttv" },
    { href: "prfc-8-hd", title: "PRFC 8 HD", logo: "prfc" },
    { href: "prfc-7-hd", title: "PRFC 7 HD", logo: "prfc" },
    { href: "prfc-6-hd", title: "PRFC 6 HD", logo: "prfc" },
    { href: "prfc-5-hd", title: "PRFC 5 HD", logo: "prfc" },
    { href: "prfc-4-hd", title: "PRFC 4 HD", logo: "prfc" },
    { href: "prfc-3-hd", title: "PRFC 3 HD", logo: "prfc" },
    { href: "prfc-2-hd", title: "PRFC 2 HD", logo: "prfc" },
    { href: "prfc-1-hd", title: "PRFC 1 HD", logo: "prfc" },
    { href: "conmebol-tv-3-hd", title: "Conmebol TV 3 HD", logo: "conmebol" },
    { href: "conmebol-tv-2-hd", title: "Conmebol TV 2 HD", logo: "conmebol" },
    { href: "conmebol-tv-1-hd", title: "Conmebol TV 1 HD", logo: "conmebol" },
    { href: "tnt", title: "TNT", logo: "tnt" },
    { href: "dazn-3", title: "DAZN 3", logo: "dazn" },
    { href: "dazn-2", title: "DAZN 2", logo: "dazn" },
    { href: "dazn", title: "DAZN", logo: "dazn" },
    { href: "espn-extra", title: "ESPN EXTRA", logo: "espn" },
    { href: "espn-4", title: "ESPN 4", logo: "espn" },
    { href: "espn-3", title: "ESPN 3", logo: "espn" },
    { href: "espn-2", title: "ESPN 2", logo: "espn" },
    { href: "espn", title: "ESPN", logo: "espn" },
    { href: "bandsport", title: "BANDSPORT", logo: "bandsports" },
    { href: "pfc-clubes-fhd", title: "PFC Clubes FHD", logo: "prfc" },
];


const streamingChannel = [
    { href: "/prime-tv-3", title: "PRIME TV 3", logo: "prime" },
    { href: "/prime-tv-2", title: "PRIME TV 2", logo: "prime" },
    { href: "/prime-tv", title: "PRIME TV", logo: "prime" },
    { href: "/paramount-plus-3", title: "Paramount Plus 3", logo: "paramount" },
    { href: "/paramount-plus-2", title: "Paramount Plus 2", logo: "paramount" },
    { href: "/paramount-plus", title: "Paramount Plus", logo: "paramount" },
    { href: "/hbo-max-5", title: "HBO MAX 5", logo: "hbomax" },
    { href: "/hbo-max-4", title: "HBO MAX 4", logo: "hbomax" },
    { href: "/hbo-max-3", title: "HBO MAX 3", logo: "hbomax" },
    { href: "/hbo-max-2", title: "HBO MAX 2", logo: "hbomax" },
    { href: "/hbo-max", title: "HBO MAX", logo: "hbomax" },
    { href: "/star-4-hd", title: "Star+ 4 HD", logo: "star" },
    { href: "/star-3-hd", title: "Star+ 3 HD", logo: "star" },
    { href: "/star-2-hd", title: "Star+ 2 HD", logo: "star" },
    { href: "/star-1-hd", title: "Star+ 1 HD", logo: "star" },
];

const channel = [
    { href: "/furacao-tv", title: "FURACAO TV", logo: "furacao" },
    { href: "/globo-rio", title: "GLOBO RIO", logo: "globorio" },
    { href: "/telecine-touch", title: "Telecine Touch", logo: "telecinetouch" },
    { href: "/telecine-cult", title: "Telecine Cult", logo: "telecinecult" },
    { href: "/hbo-pop", title: "HBO POP", logo: "hbopop" },
    { href: "/hbo-2", title: "HBO 2", logo: "hbo2" },
    { href: "/tnt", title: "TNT", logo: "tnt" },
    { href: "/animal-planet", title: "ANIMAL PLANET", logo: "animalplanet" },
    { href: "/investigacao-discovery", title: "Investigacão Discovery", logo: "discoveryid" },
    { href: "/discovery-turbo", title: "Discovery Turbo", logo: "discoveryturbo" },
    { href: "/space", title: "SPACE", logo: "space" },
    { href: "/national-geographic", title: "National Geographic", logo: "nationalgeo" },
    { href: "/tooncast", title: "Tooncast", logo: "tooncast" },
    { href: "/gloobinho", title: "GLOOBINHO", logo: "gloobinho" },
    { href: "/gloob", title: "GLOOB", logo: "gloob" },
    { href: "/nick-jr", title: "NICK JR" },
    { href: "/nickelodeon", title: "NICKELODEON" },
    { href: "/hbo-mundi", title: "HBO MUNDI" },
    { href: "/hbo-family", title: "HBO FAMILY" },
    { href: "/hbo-xtreme", title: "HBO XTREME" },
    { href: "/hbo-signature", title: "HBO SIGNATURE" },
    { href: "/globo-minas", title: "GLOBO MINAS" },
    { href: "/comedy-central", title: "COMEDY CENTRAL" },
    { href: "/bandnews", title: "BANDNEWS" },
    { href: "/warner-channel", title: "WARNER CHANNEL" },
    { href: "/redetv", title: "REDETV" },
    { href: "/disney-channel", title: "Disney Channel" },
    { href: "/hbo-plus", title: "HBO PLUS" },
    { href: "/hbo", title: "HBO" },
    { href: "/bandsport", title: "BANDSPORT" },
    { href: "/megapix", title: "MEGAPIX" },
    { href: "/history-channel", title: "History Channel" },
    { href: "/discovery-kids", title: "Discovery Kids" },
    { href: "/star-life-hd", title: "Star Life HD" },
    { href: "/cartoon-network", title: "Cartoon Network" },
    { href: "/tnt-series", title: "TNT Series" },
    { href: "/multishow", title: "Multishow" },
    { href: "/h2", title: "H2" },
    { href: "/combate", title: "Combate" },
    { href: "/discovery-channel-hd", title: "Discovery Channel HD" },
    { href: "/disney-xd", title: "Disney XD" },
    { href: "/br-globo-news-hd", title: "BR: Globo News HD" },
    { href: "/star-channel-hd", title: "Star Channel HD" },
    { href: "/cnn-brasil-hd", title: "CNN Brasil HD" },
    { href: "/telecine-fun-hd", title: "Telecine Fun HD" },
    { href: "/telecine-premium-hd", title: "Telecine Premium HD" },
    { href: "/telecine-pipoca-hd", title: "Telecine Pipoca HD" },
    { href: "/telecine-action-hd", title: "Telecine Action HD" },
    { href: "/fox-sport-2-hd", title: "FOX SPORT 2 HD " },
    { href: "/sportv-3-hd", title: "SPORTV 3 HD" },
    { href: "/sportv-2-hd", title: "SPORTV 2 HD" },
    { href: "/sportv-hd", title: "SPORTV HD " },
    { href: "/sbt", title: "SBT" },
    { href: "/band-tv-sp", title: "BAND TV SP" },
    { href: "/record-tv-sp", title: "Record TV SP" },
    { href: "/globo-sp", title: "Globo SP" }
]